name: CI Pipeline
on: [push]  # Runs on every push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install flask pytest
      - run: pytest test_app.py -v